BHGContractorModule/Contractor.Web/Models/Property/HealthAndSafety/AsbestosDetailViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Contractor.Web.Models
{
    public class AsbestosDetailViewModel
    {
        [Display(Name = "asbestosId")]
        public int asbestosId { get; set; }

        [Display(Name = "employeeId")]
        public int? employeeId { get; set; }

        [Display(Name = "Asbestos Type")]
        [Required(ErrorMessage = "Please select asbestos type")]
        public int? asbestosTypeId { get; set; }

        [Display(Name = "Asbestos Type")]
        public string asbestosType { get; set; }

        [Display(Name = "Asbestos Elements")]
        [Required(ErrorMessage = "Please select asbestos element")]
        public int? asbestosElementId { get; set; }

        [Display(Name = "Asbestos Element")]
        public string asbestosElement { get; set; }

        [Display(Name = "Type")]
        [Required(ErrorMessage = "Please select type")]
        public string typeId { get; set; }

        [Display(Name = "Type")]
        public string type { get; set; }

        [Display(Name = "Risk Level")]
        [Required(ErrorMessage = "Please select risk level")]
        public int? riskLevelId { get; set; }

        [Display(Name = "Risk Level")]
        public string riskLevel { get; set; }

        [Display(Name = "Added")]
        [Required(ErrorMessage = "Please select added date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public string addedDate { get; set; }

        [Display(Name = "Removed")]        
        public string removedDate { get; set; }

        [Display(Name = "Notes")]
        public string notes { get; set; }

        [Display(Name = "Urgent Action Required?")]
        public bool? isUrgentActionRequired { get; set; }

        [Display(Name = "createdBy")]
        public int? createdBy { get; set; }

        [Display(Name = "Created By Employee Name")]
        public string createdByEmployeeName { get; set; }

        public string createdByFullName { get; set; }
        

        public string ModelDateFormate { get; set; } = "{0:dd/MM/yyyy}";

    }
}

BHGContractorModule/Contractor.Web/Models/Property/HealthAndSafety/AsbestosDocumentViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Contractor.Web.Models
{
    public class AsbestosDocumentViewModel
    {
        [Display(Name = "Category")]
        [Required(ErrorMessage = "Please select category")]
        public string documentCategory { get; set; }

        [Display(Name = "Type")]
        [Required(ErrorMessage = "Please select document type")]
        public int documentTypeId { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "Please select title")]
        public int? documentSubTypeId { get; set; }

        [Display(Name = "Document")]
        [Required(ErrorMessage = "Please select document date")]
        public string documentDate { get; set; }

        [Display(Name = "Expiry")]
        [Required(ErrorMessage = "Please select expiry date")]
        public string expiryDate { get; set; }

        [Display(Name = "Keywords")]
        public string keywords { get; set; }

        [Required(ErrorMessage = "Document is required")]
        public HttpPostedFileBase file { get; set; }

    }
}

BHGContractorModule/Contractor.Web/Controllers/HealthAndSafety/HealthAndSafetyController.cs
using AutoMapper;
using Contractor.BusinessLogic;
using Contractor.BusinessObject;
using Contractor.Utilities.Constant;
using Contractor.Utilities.Helper;
using Contractor.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Contractor.Web.Controllers.HealthAndSafety
{
    public class HealthAndSafetyController : BaseController
    {

        public HealthAndSafetyController(IManagerProxy manager) : base(manager)
        {

        }

        #region "Controller Method"

        #region "Index"
        // GET: HealthAndSafety
        public ActionResult Index(string id, string type)
        {
            if (IsValidRequest(id))
            {
                HealthAndSafetyViewModel asbestosListing = GetAsbestosList(id);
                return PartialView("~/Views/Property/HealthAndSafety/_Asbestos.cshtml", asbestosListing);
            }
            else
            {
                return new HttpNotFoundResult();
            }

        }
        #endregion

        #region "Get Asbestos By Id"
        public JsonResult GetAsbestosById(int Id)
        {
            HealthAndSafetyViewModel model = new HealthAndSafetyViewModel();
            AsbestosDetailViewModel detail = new AsbestosDetailViewModel();
            model = (HealthAndSafetyViewModel)Session[SessionConstants.HealthAndSafetyInfo];
            detail = model.asbestosList.asbestosList.SingleOrDefault(c => c.asbestosId == Id);
            return Json(detail, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region "Search Asbestos"
        public ActionResult SearchAsbestos(string id)
        {
            HealthAndSafetyViewModel model = GetAsbestosList(id);
            return PartialView("~/Views/Property/HealthAndSafety/_AsbestosListing.cshtml", model.asbestosList);
        }
        #endregion

        #region "Add/Amend Asbestos"

        [HttpPost]
        public ActionResult AddAmendAsbestos(AsbestosDetailViewModel asbestosDetail)
        {
            var response = "";            
            asbestosDetail.createdBy = GetUserIdFromSession();

            var request = Mapper.Map<AsbestosDetailViewModel, AsbestosDetailRequest>(asbestosDetail);

            PropertyDetailRequest propertyRequest = GetPropertyDetailRequestParams();
            request.schemeId = propertyRequest.schemeId;
            request.blockId = propertyRequest.blockId;
            request.propertyId = propertyRequest.propertyId;

            this.Managers.HealthAndSafetyManager.AddAmendAsbestos(request);
            response = UserMessageConstants.AsbestosSuccessMessage;

            if (asbestosDetail.isUrgentActionRequired.HasValue && asbestosDetail.isUrgentActionRequired.Value == true)
            {
                var emailResponse = sendEmailNotificationOnUrgentAction(asbestosDetail);
                if (emailResponse == "Ok" || emailResponse == "NaN")
                {
                    return Json(response, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(emailResponse, JsonRequestBehavior.AllowGet);
                }
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region "Add Document"

        public ActionResult AddDocument(HealthAndSafetyViewModel docDetail)
        {
            var response = "";
            var documentInfo = docDetail.asbestosDocument;

            if (documentInfo.file != null && documentInfo.file.ContentLength > 0)
                try
                {
                    #region "Directory setup & saving document functionality"

                    PropertyDetailRequest propertyRequest = GetPropertyDetailRequestParams();
                    string directorypath = SetupDirectoryPath();
                    string fileName = FileHelper.getUniqueFileName(documentInfo.file.FileName);
                    string path = Path.Combine(string.Format("{0}\\", directorypath), fileName);
                    documentInfo.file.SaveAs(path);

                    ViewBag.Message = "File uploaded successfully";

                    #endregion

                    #region "Saving info in database"
                    var request = new AsbestosDocumentRequest();
                    request = Mapper.Map<AsbestosDocumentViewModel, AsbestosDocumentRequest>(documentInfo);
                    request.schemeId = propertyRequest.schemeId;
                    request.blockId = propertyRequest.blockId;
                    request.propertyId = propertyRequest.propertyId;

                    request.documentPath = fileName;
                    request.documentSize = FileHelper.getFileSize(documentInfo.file);
                    request.documentFormat = Path.GetExtension(fileName).Replace(".", "");
                    request.documentName = fileName;
                    request.uploadedBy = GetUserIdFromSession();

                    this.Managers.HealthAndSafetyManager.AddAsbestosDocument(request);
                    response = UserMessageConstants.DocumentSuccessMessage;
                    #endregion

                }
                catch (Exception ex)
                {
                    response = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                response = "You have not specified a file.";
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }


        #endregion

        #endregion

        #region "Helper Method"

        #region "Send Email notification on Urgent Action Required"
        private string sendEmailNotificationOnUrgentAction(AsbestosDetailViewModel asbestosDetail)
        {
            try
            {
                // property address
                // specific job role persons email address
                var request = new AsbestosEmailNotificationsRequest();
                request.propertyId = SessionManager.GetSearchValue();
                request.requestType = SessionManager.GetRequestType();
                //var employeeEmailForAsbestosDS = new DataSet();
                var employeeEmailForAsbestos = this.Managers.HealthAndSafetyManager.GetEmployeeEmailForAsbestosEmailNotifications(request);
                if (employeeEmailForAsbestos.Employee != null && employeeEmailForAsbestos.Employee.Count > 0)
                {
                    foreach (var item in employeeEmailForAsbestos.Employee)
                    {
                        if (!string.IsNullOrEmpty(item.workEmail))
                        {
                            // send email
                            var mailMessage = new MailMessage();
                            mailMessage.Subject = ApplicationConstants.UrgentAsbestosEmailSubject;

                            // load email body

                            var body = new StringBuilder();
                            StreamReader reader = new StreamReader(Server.MapPath("~/Email/AsbestosUrgentAction.htm"));
                            body.Append(reader.ReadToEnd());

                            //==========================================='
                            // Employee Name
                            body.Replace("{FULLNAME}", item.fullName);
                            // Property Address
                            body.Replace("{PROPERTYADDRESS}", item.PropertyAddress);
                            //==========================================='
                            // There is an asbestos present at the below property. Please contact Broad land Housing for details.
                            // Attach logo images with email
                            //==========================================='

                            var logoBroadLandRepairs = new LinkedResource(Server.MapPath("~/Content/Images/broadland.png"));
                            logoBroadLandRepairs.ContentId = "logoBroadLandRepairs_Id";

                            body = body.Replace("{Logo_Broadland-Housing-Association}", String.Format("cid:{0}", logoBroadLandRepairs.ContentId));

                            var mimeType = new ContentType("text/html");
                            var alternatevw = AlternateView.CreateAlternateViewFromString(body.ToString(), mimeType);
                            alternatevw.LinkedResources.Add(logoBroadLandRepairs);

                            //'==========================================='

                            // For a graphical view with logos, alternative view will be visible, body is attached for text view.
                            mailMessage.To.Add(new MailAddress(item.workEmail, item.fullName));
                            mailMessage.Body = body.ToString();
                            mailMessage.AlternateViews.Add(alternatevw);
                            mailMessage.IsBodyHtml = true;
                            EmailHelper.sendEmail(ref mailMessage);
                        }
                    }

                    return "Ok";
                }

                return "NaN";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        #endregion

        #region "Setup Directory"
        private string SetupDirectoryPath()
        {
            PropertyDetailRequest propertyRequest = GetPropertyDetailRequestParams();
            string directorypath = string.Empty;
            if (propertyRequest.type.Equals(ApplicationConstants.TypeProperty))
            {
                directorypath = FileHelper.getFileDirectoryPath(propertyRequest.type, propertyRequest.propertyId);
                FileHelper.createDirectory(directorypath);
            }
            else if (propertyRequest.type.Equals(ApplicationConstants.TypeBlock))
            {

BHGContractorModule/Contractor.Web/Controllers/PropertyController.cs
using Contractor.BusinessLogic;
using Contractor.BusinessObject;
using Contractor.BusinessObject.Property;
using Contractor.Utilities.Constant;
using Contractor.Utilities.Helper;
using Contractor.Web.Models;
using Contractor.Web.Models.Property;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Contractor.Web.Controllers
{
    public class PropertyController : BaseController
    {

        public PropertyController(IManagerProxy manager) : base(manager)
        {

        }

        // GET: Property
        public ActionResult Search()
        {
            var model = new PropertySearchViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Search(PropertySearchViewModel model)
        {
            PropertySearchRequest resquest = new PropertySearchRequest();
            resquest.Search = model.Search;
            var response = this.Managers.PropertiesManager.SearchProperty(resquest);
            model.Properties = response.Properties.Where(e => e.PropertyType == "Property").Select(e => new PropertySearchListViewModel()
            {
                SearchText = model.Search,
                Address = e.Address,
                Id = e.Id,
                PropertyType = e.PropertyType,
                TypeDescription = e.TypeDescription
            }).ToList();
            model.Schemes = response.Properties.Where(e => e.PropertyType == "Scheme").Select(e => new PropertySearchListViewModel()
            {
                SearchText = model.Search,
                Address = e.Address,
                Id = e.Id,
                PropertyType = e.PropertyType,
                TypeDescription = e.TypeDescription
            }).ToList();
            model.Blocks = response.Properties.Where(e => e.PropertyType == "Block").Select(e => new PropertySearchListViewModel()
            {
                SearchText = model.Search,
                Address = e.Address,
                Id = e.Id,
                PropertyType = e.PropertyType,
                TypeDescription = e.TypeDescription
            }).ToList();
            return PartialView("~/Views/Property/PropertyList.cshtml", model);
        }

        public ActionResult PropertyDetail(string id, string type)
        {
            var model = new PropertyDetailViewModel();
            model.id = id;
            model.type = type;
            SessionManager.SetRequestType(type.ToLower());
            SessionManager.SetSearchValue(id);

            var request = GetPropertyDetailRequestParams();
            var address = string.Empty;
            if (request.type.Equals(ApplicationConstants.TypeProperty))
            {
                address = this.Managers.PropertiesManager.GetPropertyAddress(request.propertyId);
            }
            else if (request.type.Equals(ApplicationConstants.TypeScheme))
            {
                address = this.Managers.SchemeManager.GetSchemeAddress(request.schemeId);
            }
            else if (request.type.Equals(ApplicationConstants.TypeBlock))
            {
                address = this.Managers.BlockManager.GetBlockAddress(request.blockId);
            }

            model.fullHeading = address;

            return View(model);
        }


        #region "Get Property Detail Request Params"
        public PropertyDetailRequest GetPropertyDetailRequestParams()
        {
            var request = new PropertyDetailRequest();
            string searchType = SessionManager.GetRequestType();
            string searchValue = SessionManager.GetSearchValue();
            request.type = searchType;

            if (searchValue != string.Empty)
            {
                string id = searchValue;
                if (searchType.Equals(ApplicationConstants.TypeScheme))
                {
                    request.schemeId = Convert.ToInt32(id);
                }
                else if (searchType.Equals(ApplicationConstants.TypeBlock))
                {
                    request.blockId = Convert.ToInt32(id);
                }
                else
                {
                    request.propertyId = id;
                }
            }

            return request;
        }
        #endregion
    }
}

BHGContractorModule/Contractor.Web/Views/Property/PropertyDetail.cshtml
@model Contractor.Web.Models.PropertyDetailViewModel
@{
    ViewBag.Title = "Detail";
    var isEdit = ViewBag.isEdit == "edit";
    AjaxOptions options = new AjaxOptions();
    options.AllowCache = false;
    options.HttpMethod = "POST";
    options.InsertionMode = InsertionMode.Replace;
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")

<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<div class="col-md-12 alert alert-success" id="message" style="display:none">
    <strong id="msgResponse"></strong>
</div>
<div class="progress-dialog" style="display:none;" id="loader">
    <img src='@Url.Content("~/Content/images/progress.gif")' />
</div>

<div class="row padding-bottom"></div>
<div style="">
    @*Heading*@
    <div class="row padding-bottom">
        <div class="col-md-12">
            <div class="portlet-black">
                <div class="row">
                    <div class="col-md-12 ">
                        <div class="col-md-12">
                            <div class="row portlet-black-head">
                                <div class="col-md-12">
                                    <h5 style="float:left; font-weight:bold;">@Model.fullHeading</h5>
                                    <span class="pull-right">
                                        <img src="~/Content/images/BackToSearch.png" />
                                        <a href='@Url.Action("Search", "Property")' style="color:white;" class="selected">Back to Search</a>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="portlet-black-body col-md-12">
                    <div class="row">
                        <div class="col-md-12 padding-bottom">
                            <b>Health & Safety  &nbsp; > &nbsp;  Asbestos</b>
                        </div>
                    </div>
                    <div class="col-md-12">
                        @Html.Action("Index", "HealthAndSafety", new { id = Model.id, type = Model.type })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        var MAX_FILE_UPLOAD_SIZE = 20971520;
        var MAX_IMAGE_UPLOAD_SIZE = 1048576;
        var ALLOWED_IMAGE_EXTENSION = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
        var ALLOWED_FILE_EXTENSION = ['pdf', 'doc', 'xls', 'txt'];

        jQuery.ajaxSetup({
            cache: false,
            beforeSend: function () {
                $('#loader').show();
            },
            complete: function () {
                $('#loader').hide();
            },
            success: function () { }
        });

        function getUrlVars() {
            var vars = [], hash;
            var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');

            for (var i = 0; i < hashes.length; i++) {
                hash = hashes[i].split('=');
                vars.push(hash[0]);
                vars[hash[0]] = hash[1];
            }


            return vars;

        }
        function popupMessage(outerElement, element, msg, type) {
            if (type == "success") {

                $("#" + outerElement).removeClass('alert-danger');
                $("#" + outerElement).addClass('alert-success');
            }
            else if ("failure") {
                $("#" + outerElement).removeClass('alert-success');
                $("#" + outerElement).addClass('alert-danger');
            }

            $("#" + element).html(msg)
            $("#" + outerElement).show().delay(8000).fadeOut();
            window.scrollTo(0, 0);
        }

    </script>
}

BHGContractorModule/Contractor.Web/Views/Property/PropertyList.cshtml
@model Contractor.Web.Models.Property.PropertySearchViewModel
@{ 
    Layout = null;
}
<div class="search-table-outer">
    @if (Model.Properties != null && Model.Properties.Count > 0)
    {
        <table class="search-table">
            <tr>
                <td class="search-td-border">
                    <img src="~/Content/images/icon_property.png" alt="Property" title="Property" style="border:none;width:50px;height:50px;" />
                </td>
                <td>
                    <table class="repeaterTable">
                        @foreach (var item in Model.Properties)
                        {
                            <tr onclick="ShowPropertySummary('@item.Id', '@item.PropertyType')">
                                <td>
                                    <span>
                                        @item.AddressDisplay
                                    </span>
                                </td>
                                <td>
                                    <span>
                                        ( Ref: @item.Id )
                                    </span>
                                </td>
                                <td>
                                    <span>
                                        :
                                    </span>
                                </td>
                                <td>
                                    <span>
                                        @item.TypeDescription
                                    </span>
                                </td>
                            </tr>
                        }
                    </table>
                </td>
            </tr>
        </table>
    }

    @if (Model.Schemes != null && Model.Schemes.Count > 0)
    {
        <table class="search-table">
            <tr>
                <td class="search-td-border">
                    <img src="~/Content/images/icon_scheme.png" alt="Scheme" title="Scheme" style="border:none;width:50px;height:50px;" />
                </td>
                <td>
                    <table>
                        @foreach (var item in Model.Schemes)
                        {
                            <tr onclick="ShowPropertySummary('@item.Id', '@item.PropertyType')">
                                <td>
                                    <span>
                                        @item.AddressDisplay
                                    </span>
                                </td>
                                <td>
                                    <span>

                                    </span>
                                </td>
                                <td>
                                    <span>
                                        :
                                    </span>
                                </td>
                                <td>
                                    <span>
                                        @item.Address
                                    </span>
                                </td>
                            </tr>
                        }
                    </table>
                </td>
            </tr>
        </table>
    }

    @if (Model.Blocks != null && Model.Blocks.Count > 0)
    {
        <table class="search-table">
            <tr>
                <td class="search-td-border">
                    <img src="~/Content/images/icon_block.png" alt="Block" title="Block" style="border:none;width:50px;height:50px;" />
                </td>
                <td>
                    <table>
                        @foreach (var item in Model.Blocks)
                        {
                            <tr onclick="ShowPropertySummary('@item.Id', '@item.PropertyType')">
                                <td>
                                    <span>
                                        @item.AddressDisplay
                                    </span>
                                </td>
                                <td>
                                    <span>

                                    </span>
                                </td>
                                <td>
                                    <span>
                                        :
                                    </span>
                                </td>
                                <td>
                                    <span>
                                        @item.Address
                                    </span>
                                </td>
                            </tr>
                        }
                    </table>
                </td>
            </tr>
        </table>
    }
</div>

BHGContractorModule/Contractor.Web/Views/Property/Search.cshtml
@model Contractor.Web.Models.Property.PropertySearchViewModel
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_PropertyLayout.cshtml";
}

<div id="search-main-content">
    <div id="search-content-wrapper">
        @Html.TextBoxFor(m => m.Search, new { @class = "searchbox", @placeholder = "Search Property, Block, Scheme", onkeyup = "TypingInterval();" })
    </div>

    <div class="roundcorner" id="fault_search_result">
        <div id="fault_result_header">
            <b>

            </b>
        </div>
    </div>
    <div id="searchgrid"></div>
</div>
<img src="~/Content/images/asbestos-contractor_background.jpg" width="2312" height="1540" class="bgimg" />

@section Scripts {
    <script type="text/javascript">

        jQuery.ajaxSetup({
            cache: false,
            beforeSend: function () {
                $('#loader').show();
            },
            complete: function () {
                $('#loader').hide();
            },
            success: function () { }
        });

        var typingTimer;                //timer identifier
        var doneTypingInterval = 1000;  //time in ms, 5 second for example
        function TypingInterval(e) {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(searchTextChanged, doneTypingInterval);
        }
        function searchTextChanged() {

            $.ajax({
                url: '@Url.Action("Search", "Property")',
                type: 'POST',
                data: {
                    Search: $('#Search').val()
                },
                success: function (resp) {
                    if (resp != undefined) {
                        console.log(resp);
                        resp = resp.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
                        $('#searchgrid').html(resp);
                    }
                },
                error: function (resp) {
                    if (resp != undefined) {
                        console.log(resp);
                    }
                }
            });
        }

        function ShowPropertySummary(id, type) {
            var url = '@Url.Action("PropertyDetail", "Property")';
            url = url + "/" + id + "?type=" + type;
            window.location = url;
            return false;
        }

    </script>
}