rsl_addons/RSLHousingBenefit/RSLHousingBenefit.Web/Controllers/HBUpload/FileUploaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RSLHousingBenefit.Interfaces.Service;
using System.IO;
using RSLHousingBenefit.Common.Helper;
using OfficeOpenXml;
using System.Net;
using Newtonsoft.Json;
using Rotativa;
using RSLHousingBenefit.Services.Services;
using RSLHousingBenefit.Models;
using RSLHousingBenefit.Models.Models;
using RSLHousingBenefit.Common.Constants;
using RSLHousingBenefit.Models.ViewModels;
using Spire.Xls;

namespace RSLHousingBenefit.Web.Controllers
{
    public class FileUploaderController : ABaseController
    {
        private IHBUploadService _hBUploadService;
        private IExceptionReportService _exceptionReportService;
        public FileUploaderController(IHBUploadService hBUploadService, IExceptionReportService exceptionReportService)
        {
            _hBUploadService = hBUploadService;
            _exceptionReportService = exceptionReportService;
        }
        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }
        [HttpPost]
        public JsonResult UploadFile(HttpPostedFileBase UploadedFile)
        {
            try
            {
                string fileName = Request.Headers["X-File-Name"];
                var fileExtention = fileName.Split('.');
                string folderName = "";
                if (fileExtention.Length == 2)
                {
                    switch (fileExtention[1])
                    {
                        case "xls":
                            folderName = "HBDoc";
                            fileName = "HBReferance" + DateTime.Now.ToString("hh_mm_ss_ffffff") + ".xlsx";
                            break;
                        case "csv":
                            folderName = "HBDoc";
                            fileName = "HBReferance" + DateTime.Now.ToString("hh_mm_ss_ffffff") + "." + fileExtention[1];
                            break;
                            //add default option 
                    }
                }
                //string fileType = Request.Headers["X-File-Type"];
                //int fileSize = Convert.ToInt32(Request.Headers["X-File-Size"]);
                System.IO.Stream fileContent = Request.InputStream;
                //string directorypath = SetupDirectoryPath(); Uncomment this line before deploying
                //System.IO.FileStream fileStream = System.IO.File.Create( directorypath + fileName); Uncomment this line before deploying

                //string projectPath = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.FullName;//remove these lines before deploying 
                string projectPath = FileHelper.getFileDirectoryPath(ApplicationConstants.TypeHBDoc);
                string filePath = Path.Combine(projectPath, folderName);//remove these lines before deploying 
                System.IO.Directory.CreateDirectory(filePath);//remove these lines before deploying 
                

                List<String> FileHeading = new List<string>();
                if (fileExtention[1].CompareTo("xls") == 0)
                {
                    Workbook workbook = new Workbook();
                    workbook.LoadFromStream(fileContent);
                    workbook.SaveToFile(filePath + "\\"+fileName , ExcelVersion.Version2013);
                    FileHeading = GetXlsFileHeadings(filePath + "\\" + fileName);
                }
                else
                {
                    System.IO.FileStream fileStream = System.IO.File.Create(filePath + "\\" + fileName);
                    fileContent.Seek(0, System.IO.SeekOrigin.Begin);
                    fileContent.CopyTo(fileStream);
                    fileStream.Dispose();
                    FileHeading = GetCsvFileHeadings(filePath + "\\" + fileName);
                }
                
                string lastHeading = FileHeading.LastOrDefault();
                var localAuthorities = _hBUploadService.GetLocalAuthorities().Select(l => new { l.DESCRIPTION, l.LOCALAUTHORITYID }).ToList();
                var jsonString = JsonConvert.SerializeObject(new { fileHeading = FileHeading, localAuthorities = localAuthorities, fileName = fileName, lastHeading= lastHeading });
                return Json(jsonString);
            }
            catch (Exception ex)
            {

                //throw new NullReferenceException();
                return Json(HttpStatusCode.BadRequest);
            }
        }
        [HttpGet]
        public ActionResult UploadFileForm()
        {
            //List<string> localAuthorities = _hBUploadService.GetLocalAuthorities().Select(l => l.DESCRIPTION).ToList();
            //ViewData["LocalAuthorities"] = localAuthorities;
            return PartialView();
        }
        [HttpPost]
        public JsonResult UploadFileForm(FormCollection collection)
        {
            try
            {
                int[] dataLocation = new int[7];
                HouseBenefitModel houseBenefitModel = new HouseBenefitModel();
                string localAuthority = collection["LocalAuthority"];
                string HBFileNameOriginal = collection["HBFileName"];
                string HBFileName = collection["HBFilePath"];
                string Transaction = collection["Transaction"];
                dataLocation[0] = Convert.ToInt32(collection["InitialRow"]);
                dataLocation[1] = Convert.ToInt32(collection["HBRefarance"]);
                dataLocation[2] = Convert.ToInt32(collection["Amount"]);
                dataLocation[3] = Convert.ToInt32(collection["PeriodStartDate"]);
                dataLocation[4] = Convert.ToInt32(collection["PeriodEndDate"]);
                dataLocation[5] = Convert.ToInt32(collection["TanantName"]);
                dataLocation[6] = Convert.ToInt32(collection["Address"]);
                var fileExtension = HBFileNameOriginal.Split('.');
                var HBFileData = new List<HouseBenefitModel>(); ;
                dynamic status;
                int uploadFileId = 0;
                string result = string.Empty;
                if (fileExtension.Length == 2)
                {
                    switch (fileExtension[1])
                    {

                        case "xls":
                            XlsFileReader xslFileReader = new XlsFileReader();
                            status = xslFileReader.ReadExcelFile(HBFileName, dataLocation);
                            result = status.Item1;
                            HBFileData = status.Item2;
                            break;
                        case "csv":
                            CsvFileReader CsvFileReader = new CsvFileReader();
                            status = CsvFileReader.ReadCsvFile(HBFileName, dataLocation);
                            result = status.Item1;
                            HBFileData = status.Item2;
                            break;
                    }
                }
                if (result == "successful")
                {
                    HouseBenefitFile houseBenefitFile = new HouseBenefitFile
                    {
                        ActualFileName = HBFileNameOriginal,
                        FileName = HBFileName,
                        LocalAuthorityId = Convert.ToInt32(localAuthority),
                        TransactionDate = Convert.ToDateTime(Transaction),
                        UploadedBy = SessionManager.GetSessionUserId(),
                        UploadedDate = DateTime.Now
                    };
                     uploadFileId = _hBUploadService.AddHBUploadFile(houseBenefitFile);                    
                    _hBUploadService.AddHBUploadFileData(HBFileData, uploadFileId);
                    _exceptionReportService.validateHBUploadedData(uploadFileId);
                }
                var jsonString = JsonConvert.SerializeObject(new { result = result, hBUploadId= uploadFileId });
                return Json(jsonString);
            }
            catch (Exception ex)
            {
                return Json(HttpStatusCode.BadRequest);
            }
        }
        public JsonResult PreviewHtml(string fileName, string lastColumn)
        {
            string folderName = "HBDoc"; ;
            //string projectPath = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.FullName;//remove these lines before deploying 
            string projectPath = FileHelper.getFileDirectoryPath(ApplicationConstants.TypeHBDoc);
            string filePath = Path.Combine(projectPath, folderName);//remove these lines before deploying 
            ExcelToHtml excelToHtml = new ExcelToHtml();
            string path = excelToHtml.ConvertToHtml(filePath, fileName,lastColumn);
            return Json(JsonConvert.SerializeObject(path));
        }
        public ActionResult partialViewResult(string fileName,string lastColumn)
        {
            try
            {
                string folderName = "HBDoc";
                //string projectPath = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.FullName;//remove these lines before deploying 
                string projectPath = FileHelper.getFileDirectoryPath(ApplicationConstants.TypeHBDoc);
                string filePath = Path.Combine(projectPath, folderName);//remove these lines before deploying 
                ExcelToHtml excelToHtml = new ExcelToHtml();
                string path = excelToHtml.ConvertToHtml(filePath, fileName,lastColumn);

                return new FilePathResult(path, "text/html");
            }
            catch (Exception ex)
            {
                return Json(HttpStatusCode.BadRequest);
            }
        }
        public ActionResult UploadList()
     {
            PaginationViewModel page = new PaginationViewModel();
          
            int pageNo = 1;
            if (HttpContext.Request.QueryString[QueryStringConstants.Page] != null

rsl_addons/RSLHousingBenefit/RSLHousingBenefit.Web/Views/FileUploader/ExceptionReport.cshtml
@model List<RSLHousingBenefit.Models.Models.ExceptionFileListModel>
@{
    Layout = "~/Views/Shared/_LayoutPDF.cshtml";

}
<table class="table table-striped">
    <thead>
        <tr>
            <th>HBRef</th>
            <th>Amount</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Tenant Name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ExceptionFile in @Model)
        {
            <tr>
                <td style="display:none"><input type="hidden" value="@ExceptionFile.HbUploadId" id="hbUploadId"></td>
                <td>@ExceptionFile.HBRef</td>
                <td>@ExceptionFile.Amount</td>
                <td>@ExceptionFile.StartDate</td>
                <td>@ExceptionFile.EndDate</td>
                <td>@ExceptionFile.TenantName</td>
                <td>@ExceptionFile.Address</td>
            </tr>
        }
        </tbody>
</table>

rsl_addons/RSLHousingBenefit/RSLHousingBenefit.Web/Views/FileUploader/UploadList.cshtml
@model IEnumerable<RSLHousingBenefit.Models.Models.UploadFileListModel>
    @{
        var grid = new WebGrid(canSort:true, rowsPerPage: ViewBag.PageSize);
        grid.Bind(Model.ToList(),autoSortAndPage:false, rowCount: ViewBag.TotalRows);
        //        grid.Pager(WebGridPagerModes.All);
    }

    @grid.GetHtml(
    //tableStyle: "table table-responsive backcolor",
    tableStyle: "table table-responsive backcolor web-grid-table-body",
    headerStyle: "wedgrid-header web-grid-th web-grid-a",
    footerStyle: "webgrid-footer",
    alternatingRowStyle: "webgrid-alternating-row webgrid-row-style-hover",
    rowStyle: "webgrid-row-style webgrid-row-style-hover",
    columns: (grid.Columns(
        grid.Column(columnName: "UploadDate", header: "Upload Date"),
        grid.Column(columnName: "LocalAuthority", header: "Local Authority"),
        grid.Column(columnName: "FileName", header: "File Name", format: @<text><span onclick="fileDownload('@item.FilePath')">@item.FileName</span></text>),
        grid.Column(columnName: "UploadBy", header: "Upload By"),
        grid.Column(columnName: "UploadRecord", header: "Upload Record"),
        grid.Column(columnName: "UploadRecordTotal", header: "Upload Record Total (£)"),
        grid.Column(columnName: "ExcludeRecord", header: "Exclude Record", format: @<text><a onclick="ShowExcludeRecords(@item.HbUploadId,@item.ExcludeRecord)">@item.ExcludeRecord</a></text>),
        grid.Column(columnName: "ExcludeRecordTotal", header: "Exclude Record Total (£) "),
        grid.Column(columnName: "OrignalRecord", header: "Orignal Record"),
        grid.Column(columnName: "OrignalRecordTotal", header: "Orignal Record Total (£)")
        )))

    <div class="panel-footer">
        <div class="row">
            <div class="col-md-3">
            </div>
            <div id="gridPager" class="space-box col-md-8">
                @grid.PagerList(WebGridPagerModes.All, rowCount: grid.Rows.Count())
            </div>
            <div id="" class="col-md-1">
                <div class="row">
                    <div class="form-inline">
                        <span for="rg-from">Page: </span>
                        <div class="form-group">
                            @Html.TextBox("pageText", "", new { Name = "pageText", Style = "width:40px;", Id = "txtPageNo", onkeyup = "TypingPageInterval();" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<!-- Exception Rreport PopUp-->
<div class="modal fade" id="ExceptionRreportModel" tabindex="-1" role="dialog" aria-labelledby="ExceptionRreportModelLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width:75%">
        <div class="modal-content">
            <div class="modal-header" style="padding: 0px;">
                <div class="row padding-bottom">
                    <div class="col-md-12">
                        <div class="col-md-12" style=" background-color: #000; padding: 10px;">
                            <span class="header" style="padding:0;font-size: large;color: white;">Exception Reprort:</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div style="height :400px; overflow:auto;" id="ExceptionRreportBody"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn-default" data-dismiss="modal" onclick="btnCancel()">Cancel</button>
                <button type="button" id="SelectFile" class="btn-default" onclick="btnDownloadPDF()">Download as PDF</button>
            </div>
        </div>
    </div>
</div>
<script>

    (function () {
        $("#webgrid a").on('click', function (event) {
            loadGridEvents(event, this);
        });

        $('thead > tr > th > a[href*="sort=@grid.SortColumn"]').parent().append('@(grid.SortDirection == SortDirection.Ascending ? "▲" : "▼")');
        $('thead > tr > th:first').addClass('dis-none');

    })();

    function loadGridEvents(event, ths) {
        event.preventDefault();
        var href = $(ths).attr("href");
        var queryString = href.substring(href.indexOf('?'), href.length);
        var requestUrl = '@Url.Action("UploadList", "FileUploader")' + queryString;
        $("#webgrid").load(requestUrl);
    }
    var typingPageTimer;                //timer identifier
    var donePagedInterval = 1000;  //time in ms, 5 second for example

    function TypingPageInterval(e) {
        typingPageTimer = setTimeout(searchPageChanged, donePagedInterval);
    }

    function searchPageChanged() {
        var rsStatus = 1;
        if ($('#rdBtnstatus').is(':checked') == false) {
            rsStatus = 0;
        } else {
            rsStatus = 1;
        }
        var requestUrl = '@Url.Action("UploadList", "FileUploader")'
       + "?page=" + $("#txtPageNo").val() + '&rdBtnstatus=' + rsStatus + '&txtSearchText=' + $("#txtSearchText").val();
        $("#webgrid").load(requestUrl);
    }
    function ShowExcludeRecords(hbUploadId,count)
    {
        if (count > 0) {
            $.ajax({
                url: '@Url.Action("ExceptionReport", "FileUploader")',
                type: "GET",
                cache: false,
                data: { hbUploadId: hbUploadId },
                success: function (response) {
                    $('#ExceptionRreportBody').html(response);
                    $("#ExceptionRreportModel").modal({ show: true });;
                },
                statusCode: {
                    400: function () {
                        alert("Error");
                    }
                }
            });
        }
    }
    function btnCancel()
    {
        $("#ExceptionRreportModel").modal({ show: false });;
    }
    function btnDownloadPDF()
    {

        var url = '@Url.Action("DownloadExceptionReport", "FileUploader")'
        var hbUploadId = $("#hbUploadId").val();
        window.location = url+"?hbUploadId=" + hbUploadId;
    }
    function fileDownload(path)
    {
        window.open(path, '_blank');
    }
</script>