rsl_addons/RSLHRModuleWeb/BHGHRModuleWeb/ViewModels/Navigation/NavigationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BHGHRModuleWeb.ViewModels
{
    public class NavigationViewModel
    {
        public string CurrentModule { get; set; }
        /// <summary>
        /// Sub Menu Items
        /// </summary>
        public List<MenuViewModel> menues { get; set; }
        /// <summary>
        /// Sub Menu Items of Customer Module
        /// </summary>
        public List<ModuleItemViewModel> hrModuleMenus { get; set; }
    }

    public class ModuleItemViewModel
    {
        /// <summary>
        /// Module ID
        /// </summary>
        public int moduleId { get; set; }
        /// <summary>
        /// Module Name
        /// </summary>
        public string moduleName { get; set; }
        /// <summary>
        /// Module Url for Page redirection
        /// </summary>
        public string url { get; set; }
    }

    public class MenuViewModel
    {
        /// <summary>
        /// Menu Id
        /// </summary>
        public int menuId { get; set; }
        /// <summary>
        /// Menu name to be shown on Top Navigation
        /// </summary>
        public string menuName { get; set; }

        /// <summary>
        /// Menu path to be redirect that page
        /// </summary>
        public string path { get; set; }
        /// <summary>
        /// List os Sub Menus
        /// </summary>
        public List<SubMenuViewModel> subMenus { get; set; } = new List<SubMenuViewModel>();
    }

    public class SubMenuViewModel
    {
        /// <summary>
        /// Parent MenuItem id
        /// </summary>
        public int menuId { get; set; }
        /// <summary>
        /// Menu text
        /// </summary>
        public string subMenuName { get; set; }
        /// <summary>
        /// Redirect Path
        /// </summary>
        public string path { get; set; }
    }
}

rsl_addons/RSLHRModuleWeb/BHGHRModuleWeb/Controllers/Common/NavigationController.cs
using BHGHRModuleWeb.ViewModels;
using BusinessModule.NetworkManagers;
using BusinessModule.NetworkObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BHGHRModuleWeb.Controllers.Common
{
    public class NavigationController : ABaseController
    {
        // GET: Navigation
        public ActionResult GetTopNavigationMenu()
        {
            var navigationManager = new NavigationManager();
            var menuDataRequest = new MenuDataRequest();
            menuDataRequest.userId = GetUserIdFromSession();
            if (Session["Module"] != null)
            {
                menuDataRequest.moduleName = Session["Module"].ToString();
            }
            var response = navigationManager.getTopNavigationMenu(menuDataRequest);
            NavigationViewModel model = new JavaScriptSerializer().Deserialize<NavigationViewModel>(response);
            model.CurrentModule = menuDataRequest.moduleName;
            if (Request.QueryString["isTeam"] != null && Convert.ToBoolean(Request.QueryString["isTeam"].ToString()))
            {
                model.menues = new List<MenuViewModel>();
            }
            return PartialView("~/Views/Shared/_Navigation.cshtml", model);
        }
    }
}

rsl_addons/RSLHRModuleWeb/BHGHRModuleWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=11" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="progress-dialog" style="display:none;" id="loader">
        <img src='@Url.Content("~/Images/progress.gif")' />
    </div>
    <div>
        <div class="col-xs-12 no-padding-sides">
            <div>
                @* TODO: *@
                @Html.Action("GetTopNavigationMenu", "Navigation")
            </div>
            <div class="margin-top-default">
                 
            </div>
        </div>
    </div>
    <div id="divBodyContainer" class="container">
        @*TODO: NextPhase*@
        <div class="col-md-12 alert alert-success" id="nextPhaseMessage" style="display:none">
            <strong>This functionality will be available in next phase!</strong>
        </div>

        @RenderBody()
    </div>

    <script type="text/javascript">

        //TODO: 
        // cache: false,
        // add this line in JQuery (load function) when jquery version update.

        jQuery.ajaxSetup({
            cache: false,
            beforeSend: function () {
                $('#loader').show();
            },
            complete: function () {
                $('#loader').hide();
            },
            success: function () { }
        });

        //TODO: NextPhase
        function nextPhase() {
            $('.nextPhase').on('click', function () {
                $(window).scrollTop(0);
                $("#nextPhaseMessage").show().delay(5000).fadeOut();
            })
        }

        function loadDatePicker() {
            $(".DatePicker").datepicker({
                showAnim: "blind",
                dateFormat: 'dd/mm/yy',
                yearRange: '1900:2050',
                changeMonth: true,
                changeYear: true,
                showOn: 'button',
                buttonImage: '@Url.Content("~/Content/images/calendar.png")',
                buttonImageOnly: true,
            });

            //$.validator.methods.date = function (value, element) {
            //    //ES - Chrome does not use the locale when new Date objects instantiated:
            //    //return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
            //    var d = new Date();
            //    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
            //}

            $.validator.methods.date = function (value, element) {
                // /^\d{4}[\/\-](0?[1-9]|1[012])[\/\-](0?[1-9]|[12][0-9]|3[01])$/.test( value );
                //old   (/^\d{1,2}[\/-]\d{1,2}[\/-]\d{4}(\s\d{2}:\d{2}(:\d{2})?)?$/.test(value)
                var valadsasd = this.optional(element) || (/^\d{1,2}[\/-]\d{1,2}[\/-]\d{4}(\s\d{2}:\d{2}(:\d{2})?)?$/.test(value)
                        && !/Invalid|NaN/.test(new Date(value.substr(6, 4) + '-' + value.substr(3, 2) + '-' + value.substr(0, 2))));
                //alert(valadsasd);
                return valadsasd;
            }

            //$.validator.methods.date = function (value, element) {
            //    var d = value.split("/");
            //    return this.optional(element) || !/Invalid|NaN/.test(new Date((/chrom(e|ium)/.test(navigator.userAgent.toLowerCase())) ? d[1] + "/" + d[0] + "/" + d[2] : value));
            //};
        }

    </script>

    @RenderSection("scripts", required: false)

</body>
</html>

rsl_addons/RSLHRModuleWeb/BHGHRModuleWeb/Views/Shared/_Navigation.cshtml
@model BHGHRModuleWeb.ViewModels.NavigationViewModel
@{ 
    var className = "";
    var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
}
<div class="TopNavigation">
    <ul>
        <li>
            <div class="asb-dropdown">
                <a href="javascript:void(0)" class="module">
                    @if (Model.CurrentModule == "MyJob")
                    {
                        <span>My Job</span>
                    }
                    else
                    {
                        <span>@Model.CurrentModule</span>
                    }
                </a>
                <div class="asb-dropdown-content" style="min-width:150px !important; margin-left:8px !important;">
                    @foreach (var m in Model.hrModuleMenus)
                    {
                        <a href="@m.url" data-id="@m.moduleId"> - @m.moduleName</a>
                    }
                </div>
            </div>
        </li>
        @if (Model.menues != null && Model.menues.Count > 0)
        {
            foreach (var item in Model.menues)
            {
                className = "";
                if (item.menuName.Equals(controllerName))
                {
                    className = "selected";
                }
                <li>
                    <div class="asb-dropdown">
                        <a href="@item.path" class="@className" data-itemid="@item.menuId">@item.menuName</a>
                        <div class="asb-dropdown-content">
                            @foreach (var subMenuItem in item.subMenus)
                            {
                                <a href="@subMenuItem.path" class="@className" data-itemid="@subMenuItem.menuId">@subMenuItem.subMenuName</a>
                            }
                        </div>
                    </div>
                </li>
            }
        }
    </ul>
</div>

<script type="text/javascript">
    //TODO: NextPhase
    (function () {
        $('.nextPhase').on('click', function () {
            $(window).scrollTop(0);
            $("#nextPhaseMessage").show().delay(5000).fadeOut();
        })
    })();

</script>